# Generated by Django 5.1.7 on 2025-05-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
