# Generated by Django 4.2.2 on 2025-06-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_delete_mymodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_add_product", "Can add product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
