# Generated by Django 4.2.2 on 2025-06-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
