# Generated by Django 4.2.2 on 2025-06-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
